# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
# Enable Analog Input
CONFIG_ADC=y
# Use async mode (Optional)
CONFIG_ADC_ASYNC=y

# Enable Analog Input Module
CONFIG_ANALOG_INPUT=y
# CONFIG_ANALOG_INPUT_LOG_LEVEL_DBG=y
# CONFIG_ANALOG_INPUT_REPORT_INTERVAL_MIN=22

# Enable logging for pre/post processed value
CONFIG_ANALOG_INPUT_LOG_DBG_RAW=y
CONFIG_ANALOG_INPUT_LOG_DBG_REPORT=y

# Just in case, you don't RTFM
CONFIG_INPUT=y

# ↓↓↓↓ Advence Settings ↓↓↓↓

# Enable using explicit ADC channels config from device tree
# - default to false
# - It allows composited channel to be used. e.g. differential with +/-vRef.
CONFIG_ANALOG_INPUT_USE_DTS_ADC_CH_CFG=n

# ADC channels resolution (in bit)
# - default to 12 bit
# - With above CONFIG_ANALOG_INPUT_USE_DTS_ADC_CH_CFG=y, it might need this 
#   to enlarge buffer of ADC sequencer for 24bit hi-res ADC.
ANALOG_INPUT_ADC_RES=12