manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com
    - name: urob
      url-base: https://github.com
    - name: infused-kim
      url-base: https://github.com

  projects:
    # Используем форк urob — он на 99% совпадает с официальным, но в нем есть мышь
    - name: zmk
      remote: urob
      revision: main
      import: app/west.yml

    # Драйвер трекпоинта
    - name: kb_zmk_ps2_mouse_trackpoint_driver
      remote: infused-kim
      revision: main

  self:
    path: config
